### ISSUE TITLE
Some Squares

### ISSUE THREAD

**Issue by fraglider91** [D4rK7355608/GoogleProductSansFont#4]
Hello, first of all your module is amazing.

I need to tell you that I have some squares in random websites. Can you re check pls?

**Comment by SunnyLeu** [comment]
I think you needs to give some example urls to let the author know what characters need to be fix.😺

**Comment by k4ustu3h** [comment]
![Screenshot_20220216-202223_Chrome.png](https://user-images.githubusercontent.com/49553711/154291026-506c394c-890f-4ec5-a6b7-fd5831226b28.png)
